name: Validate Model Files

on:
  pull_request:
    paths:
      - 'models/**/*.yaml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install jsonschema & PyYAML
        run: pip install jsonschema pyyaml
      - name: Validate YAML files
        run: |
          python .github/scripts/validate_models.py
